config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls')),
    path('', include('content.urls')),
    # path('accounts/', include('instagram_auth.urls')),
]

user/urls.py
from django.urls import path
from . import views




app_name = 'auth'
urlpatterns = [
    # path('emailsignup/', views.clsRegisterView.as_view(), name='register-view'), ##class view
    path('emailsignup/', views.RegisterView, name='register-view'), ##function view
    path('login/', views.LoginView, name='login-view')
]

user/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.validators import UnicodeUsernameValidator
from lib.common_models import BaseModel



class User(AbstractBaseUser, BaseModel, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    fullname = models.CharField(_("full name"), max_length=256, blank=False, null=False, unique=False)
    email = models.EmailField(_("email address"), blank=True)
    phone_number = models.CharField(_('phone number'), max_length=11, blank=True) # need an validator
    avatar = models.ImageField( _('avatar'), upload_to='users/avatars/', blank=True,
                                validators=[FileExtensionValidator(allowed_extensions=('png', 'jpeg', 'jpg', 'webp')) ])
    bio = models.TextField(_('biography'), blank=True)
    web_site = models.URLField(_('web site'), blank=True)
    is_verified = models.BooleanField(_('verify'), blank=True, default=False)


    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        return self.username

    def get_short_name(self):
        """Return the short name for the user."""
        return self.username


user/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login
from django.http.response import HttpResponseNotAllowed
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from .form import RegisterForm, LoginForm

from lib.http_method import get_next_page

#
#
# from django.views.generic import FormView
# class clsRegisterView(FormView):
#     form_class = RegisterForm
#     template_name = "instagram_auth/register.html"
#     success_url = redirect(reverse('instagram_auth:login-view'))
#
#     def form_valid(self, form):
#         form.save() # save changes in db
#         messages.success(self.request, _("successful registration."))
#         return super().form_valid(form)
#

def RegisterView(request):
    ctx = {
        "form": RegisterForm()
    }
    next = get_next_page(request=request) or reverse('auth:login-view')

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if not form.is_valid():
            ctx["form"] = form
            messages.warning(request, _("missing value. invalid form"))
            return render(request, "instagram_auth/register.html", context=ctx)

        form.save()
        messages.success(request, _("successful registration."))
        return redirect(next)

    elif request.method == "GET":
        return render(request, "instagram_auth/register.html", context=ctx)
    else:
        return HttpResponseNotAllowed("Method not allowed")

def LoginView(request):
    ctx = {
        "form": LoginForm()
    }

    next = get_next_page(request=request) or reverse('auth:login-view')

    if request.method == "POST":
        form = LoginForm(request.POST)
        if not form.is_valid():
            ctx["form"] = form
            return render(request, "instagram_auth/login.html", context=ctx)

        username = form.cleaned_data["EmailOrPhone"]
        password = form.cleaned_data["Password"]
        user = authenticate(request=request, username=username, password=password)

        if not user:
            messages.warning(request, _("invalid credential! ."))
            return redirect(next)

        login(request=request, user=user)
        messages.success(request, _("welcome back {}".format(user.fullname)))
        return redirect(next)

    elif request.method == "GET":
        return render(request, "instagram_auth/login.html", context=ctx)
    else:
        return HttpResponseNotAllowed("Method not allowed")


user/templates/instagram_auth/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login • Instagram{% endblock title %}

{% block style %}
    <style>
    .form-control{
        background-color: var(--bs-secondary-bg);
    }
    </style>
{% endblock style %}

{% block content %}
    <section>
        <div class="container-fluid">
            <div class="row flex-column justify-content-center align-items-center">

                <div class="col-md-3 col-lg-2 col-sm-11 col-12 border-dark-50 border mt-5 p-5 p-md-4">
                    {% include 'components/alert.html' %}
                    <div class="card-header-register d-flex flex-column justify-content-center align-items-center">
                        <img style="width: 70%" class="p-1 my-3" src="{% static 'media/typo.png' %}">
                    </div>

                    <form class="mt-1" method="post" action="{{ form.action }}">
                        {% csrf_token %}
                        {{ form.EmailOrPhone }}
                        {{ form.Password }}
                        <input type="submit" class="btn btn-primary w-100 fs-0-8 my-3" value="{{ form.SubmitText }}">
                    </form>

                    <div class="seprator d-flex justify-content-center align-items-center my-1">
                        <hr class="bg-dark w-100">
                        <span class="text-muted px-3  fw-bold fs-0-9"> OR </span>
                        <hr class="bg-dark w-100">
                    </div>
                    <div class="text-center fs-0-9 mt-3">
                        <p class="text-primary"><i class="bi bi-facebook"></i> Log in with Facebook</p>
                        <a class="text-muted fs-0-8 text-decoration-none" href="#">forgot password?</a>
                    </div>

                </div>
                <div class="col-md-3 col-lg-2 col-sm-11 col-12 border-dark-50 border my-2 px-4 py-3">
                    <p class="text-center my-2 fs-0-9">Don't have an account? ? <a href="{% url 'auth:register-view' %}" class="text-decoration-none">Sing up</a></p>
                </div>
                <div class="col-md-3 col-lg-2 col-sm-11 col-12 my-2">
                    <p class="text-center m-0 fs-0-9">Get the app</p>
                    <div class="d-flex justify-content-center align-items-center">
                        <img style="width: 50%" src="{% static 'media/getit-from-google-play.png' %}" class="p-1">
                        <img style="width: 50%" src="{% static 'media/getit-from-microsoft-store.png' %}" class="p-3">
                    </div>
                </div>

            </div>


            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            {% include 'components/auth/footer.html' %}
        </div>
    </section>
{% endblock content %}

{% block script %}
{% endblock script %}

user/templates/instagram_auth/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sign up • Instagram{% endblock title %}

{% block style %}
    <style>
    .form-control{
        background-color: var(--bs-secondary-bg);
    }
    </style>
{% endblock style %}

{% block content %}
    <section>
        <div class="container-fluid">
            <div class="row flex-column justify-content-center align-items-center">

                <div class="col-md-3 col-lg-2 col-sm-11 col-12 border-dark-50 border mt-3 p-5 p-md-4">
                    {% include 'components/alert.html' %}
                    <div class="card-header-register d-flex flex-column justify-content-center align-items-center">
                        <img style="width: 70%" class="p-1" src="{% static 'media/typo.png' %}">
                        <p class="text-muted text-center fw-bold my-4 fs-0-9">Sign up to see photos and videos from your friends.</p>
                        <button class="btn btn-primary w-100 fw-bold fs-0-9"><i class="bi bi-facebook"></i> Log in with Facebook</button>
                    </div>
                    <div class="seprator d-flex justify-content-center align-items-center my-1">
                        <hr class="bg-dark w-100">
                        <span class="text-muted px-3  fw-bold fs-0-9"> OR </span>
                        <hr class="bg-dark w-100">
                    </div>
                    <form class="mt-1" method="post" action="{{ form.action }}">
                        {% csrf_token %}
                        {{ form.EmailOrPhone }}
                        {% if form.EmailOrPhone.errors %}
                            <ul>
                            {% for err in form.EmailOrPhone.errors %}
                                <li class="text-danger fs-0-8">{{ err }}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        {{ form.FullName }}
                        {% if form.FullName.errors %}
                            <ul>
                            {% for err in form.FullName.errors %}
                                <li class="text-danger fs-0-8">{{ err }}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        {{ form.Username }}
                        {% if form.Username.errors %}
                            <ul>
                            {% for err in form.Username.errors %}
                                <li class="text-danger fs-0-8">{{ err }}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        {{ form.Password }}
                        {% if form.Password.errors %}
                            <ul>
                            {% for err in form.Password.errors %}
                                <li class="text-danger fs-0-8">{{ err }}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        <p class="text-muted my-4 text-center fs-0-8">People who use our service may have uploaded your contact information to Instagram. <a class="text-dark" href="#">Learn More</a></p>
                        <p class="text-muted my-4 text-center fs-0-8">By signing up, you agree to our <a class="text-dark " href="#">Terms</a> , <a class="text-dark " href="#">Privacy Policy</a> and <a class="text-dark " href="#">Cookies Policy</a> .</p>
                        <input type="submit" class="btn btn-primary w-100 fs-0-8" value="{{ form.SubmitText }}">
                    </form>
                </div>
                <div class="col-md-3 col-lg-2 col-sm-11 col-12 border-dark-50 border my-2 px-4 py-3">
                    <p class="text-center my-2 fs-0-9">Have an account? <a href="{% url 'auth:login-view' %}" class="text-decoration-none">Log in</a></p>
                </div>
                <div class="col-md-3 col-lg-2 col-sm-11 col-12 my-2">
                    <p class="text-center m-0 fs-0-9">Get the app</p>
                    <div class="d-flex justify-content-center align-items-center">
                        <img style="width: 50%" src="{% static 'media/getit-from-google-play.png' %}" class="p-1">
                        <img style="width: 50%" src="{% static 'media/getit-from-microsoft-store.png' %}" class="p-3">
                    </div>
                </div>

            </div>
            {% include 'components/auth/footer.html' %}
        </div>
    </section>
{% endblock content %}

{% block script %}
{% endblock script %}